### PR TITLE
p: add S function and method

### PR DESCRIPTION
**Pull request by zchee**
p: add S function and method.

### CODE REVIEW

**Comment by Code-Hex** [comment]
@zchee Thanks for your PR!
I want to know what is the usecase for this function? Isn't enough `dd.Dump`?
I understand this is returned colored string. but I couldn't think of a usecase

**Comment by zchee** [comment]
like, 

```go
fmt.Errorf("foobarwrappedmsg: dump: %s: %w", p.S("..."), err)
```

**Comment by Code-Hex** [comment]
@zchee So... you want to use it in the error information. right? like for CLI

**Comment by zchee** [comment]
yep.

dd is debug package. it's my coding style, but I want to dump any values when occurred some errors.

**Comment by zchee** [comment]
ah, not only error, any value related that errors.
I want to dump when returns error.

**Comment by Code-Hex** [comment]
@zchee dd package is not just debugging purpose. It also has code generator purpose. So dd.Dump returns string value for the type.

You're PR seems to be attached with color escape sequence code. So I don't think it is helpful when you see logs if not on CLI (e.g. on the Google Cloud Logging).

So I just want to know usecases

**Comment by zchee** [comment]
@Code-Hex Hmm, okay. I understand your opinions. close it.

**Pull request closed without merging**
